import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, test } from 'vitest'

const html = readFileSync(resolve(process.cwd(), 'plugins/themes/dogeared/guiHTML.html'), 'utf8')
const css = readFileSync(resolve(process.cwd(), 'plugins/themes/dogeared/customCSS.css'), 'utf8')

describe('dogeared theme contract', () => {
    test('keeps required risu template tags', () => {
        expect(html).toContain('<risuicon></risuicon>')
        expect(html).toContain('<risutextbox></risutextbox>')
        expect(html).toContain('<risubuttons></risubuttons>')
        expect(html).toContain('<risugeninfo></risugeninfo>')
    })

    test('uses bookmark and reader layout containers', () => {
        expect(html).toContain('reader-bookmark')
        expect(html).toContain('reader-banner')
        expect(html).toContain('reader-banner-art')
        expect(html).toContain('reader-main')
        expect(html).toContain('reader-meta')
        expect(html).toContain('reader-body')
    })

    test('separates top identity/meta from bottom action bar', () => {
        expect(html).toContain('reader-header')
        expect(html).toContain('reader-actions')
        expect(html).toMatch(/reader-body[\s\S]*reader-actions/)
    })

    test('scopes button styling so info text stays visible', () => {
        expect(css).toMatch(/\.reader-info button\s*\{/)
        expect(css).toMatch(/\.reader-buttons button\s*\{/)
        expect(css).not.toMatch(/\.header-pill button/)
        expect(css).not.toMatch(/\.scroll-right button/)
    })

    test('styles name as title text and model info as a lighter caption', () => {
        expect(css).toMatch(/Source Serif 4/)
        expect(css).toMatch(/\.reader-meta\s*\{[\s\S]*align-items:\s*center/)
        expect(css).not.toMatch(/\.reader-titleblock::before\s*\{/)
        expect(css).toMatch(/\.reader-name\s*\{[\s\S]*font-family:\s*var\(--dg-body-font\)\s*!important/)
        expect(css).toMatch(/\.reader-name,\s*\n\.reader-name \*\s*\{[^}]*font-family:\s*var\(--dg-body-font\)\s*!important/)
        expect(css).toMatch(/\.reader-name span\s*\{[^}]*font-family:\s*var\(--dg-body-font\)\s*!important/)
        expect(css).toMatch(/\.reader-name\s*\{[\s\S]*font-size:\s*19px/)
        expect(css).toMatch(/\.reader-name span\s*\{[\s\S]*padding:\s*0/)
        expect(css).toMatch(/\.reader-name span\s*\{[\s\S]*background:\s*transparent/)
        expect(css).toMatch(/\.reader-name-char span\s*\{[\s\S]*color:\s*var\(--dg-ink\)/)
        expect(css).toMatch(/\.reader-name-user span\s*\{[\s\S]*color:\s*var\(--dg-ink\)/)
        expect(css).toMatch(/\.reader-info\s*\{[\s\S]*background:\s*transparent/)
        expect(css).toMatch(/\.reader-info\s*\{[\s\S]*border:\s*none/)
        expect(css).toMatch(/\.reader-info button\s*\{[\s\S]*font-family:\s*var\(--dg-body-font\)\s*!important/)
        expect(css).toMatch(/\.reader-info > div\s*\{[^}]*display:\s*flex\s*!important[^}]*align-items:\s*center\s*!important/)
        expect(css).toMatch(/\.reader-info button span,\s*\n\.reader-info span,\s*\n\.reader-info div\s*\{[^}]*font-family:\s*var\(--dg-body-font\)\s*!important/)
        expect(css).toMatch(/\.reader-info button\s*\{[\s\S]*font-size:\s*11px/)
        expect(css).toMatch(/\.reader-info button\s*\{[\s\S]*color:\s*var\(--dg-muted\)\s*!important/)
    })

    test('uses BookkMyungjo for prose and gives paragraphs a justified novel rhythm', () => {
        expect(css).toMatch(/BookkMyungjo/)
        expect(css).toMatch(/--dg-body-size:\s*15\.25px/)
        expect(css).toMatch(/--dg-line-height:\s*1\.84/)
        expect(css).toMatch(/\.reader-body\s*\{[\s\S]*text-align:\s*justify/)
        expect(css).toMatch(/\.reader-body\s*\{[\s\S]*padding-top:\s*0\.82rem/)
        expect(css).toMatch(/\.reader-body\s*\{[\s\S]*padding-bottom:\s*1\.08rem/)
        expect(css).toMatch(/\.reader-body p,\s*\n\.reader-body li,\s*\n\.reader-body span,\s*\n\.reader-body em,\s*\n\.reader-body strong\s*\{[\s\S]*font-family:\s*var\(--dg-body-font\)\s*!important/)
        expect(css).toMatch(/\.reader-body,\s*\n\.reader-body p,\s*\n\.reader-body li,/)
        expect(css).toMatch(/\.reader-body p\s*\{[\s\S]*text-indent:\s*1em/)
        expect(css).toMatch(/\.reader-body p\s*\{[\s\S]*margin:\s*0 0 0\.5em 0/)
        expect(css).toMatch(/\.reader-body li\s*\{[\s\S]*margin:\s*0 0 0\.5em 0/)
        expect(css).toMatch(/\.reader-body strong\s*\{[\s\S]*font-weight:\s*700/)
        expect(css).toMatch(/\.reader-body em\s*\{[\s\S]*font-style:\s*italic/)
        expect(css).toMatch(/mark\[risu-mark="quote1"\]/)
        expect(css).toMatch(/mark\[risu-mark="quote2"\]/)
        expect(css).toMatch(/\.reader-body mark\[risu-mark="quote1"\]\s*\{[\s\S]*background:\s*rgba\(/)
        expect(css).toMatch(/\.reader-body mark\[risu-mark="quote2"\]\s*\{[\s\S]*background:\s*rgba\(/)
        expect(css).toMatch(/\.reader-body mark\[risu-mark="quote1"\],\s*\n\.reader-body mark\[risu-mark="quote2"\]\s*\{[\s\S]*padding:\s*0\.02em 0\.2em/)
        expect(css).toMatch(/\.reader-body mark\[risu-mark="quote1"\],\s*\n\.reader-body mark\[risu-mark="quote2"\]\s*\{[\s\S]*font-family:\s*var\(--dg-body-font\)\s*!important/)
    })

    test('overrides senderIcon inner box so bookmark art is not square', () => {
        expect(css).toMatch(/\.reader-bookmark-art > div\s*\{/)
        expect(css).toMatch(/border-radius:\s*inherit\s*!important/)
        expect(css).toMatch(/width:\s*100%\s*!important/)
        expect(css).toMatch(/height:\s*100%\s*!important/)
    })

    test('lets prose use the panel width instead of leaving a large right gutter', () => {
        expect(css).toMatch(/--dg-card-width:\s*60rem/)
        expect(css).toMatch(/\.reader-card\s*\{[\s\S]*width:\s*min\(97\.5%, var\(--dg-card-width\)\)/)
        expect(css).toMatch(/\.reader-shell\s*\{[\s\S]*padding:\s*1\.08rem 1\.08rem 1\.16rem 0\.94rem/)
        expect(css).toMatch(/\.reader-body\s*\{[\s\S]*width:\s*100%/)
        expect(css).toMatch(/max-width:\s*none/)
    })

    test('switches mobile to a banner-led reading layout', () => {
        expect(css).toMatch(/@media \(max-width: 640px\)/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*--dg-body-size:\s*14\.5px/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*--dg-line-height:\s*1\.76/)
        expect(css).toMatch(/\.reader-banner\s*\{[\s\S]*display:\s*none/)
        expect(css).toMatch(/\.reader-banner-art\s*\{/)
        expect(css).toMatch(/\.reader-shell\s*\{[\s\S]*grid-template-columns:/)
        expect(css).toMatch(/\.reader-bookmark-art\s*\{[\s\S]*height:\s*154px/)
        expect(css).toMatch(/\.reader-bookmark-art\s*\{[\s\S]*width:\s*64px/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-banner\s*\{[\s\S]*display:\s*block/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-bookmark-art\s*\{[\s\S]*display:\s*none/)
        expect(css).not.toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-banner-art\s*\{[\s\S]*clip-path:/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-shell\s*\{[\s\S]*padding:\s*0 0\.72rem 0\.84rem/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-shell\s*\{[\s\S]*border-top:\s*none/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-shell\s*\{[\s\S]*border-left:\s*none/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-shell\s*\{[\s\S]*border-right:\s*none/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-banner\s*\{[\s\S]*margin:\s*0 calc\(-0\.72rem - 1px\) -1\.3rem/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-banner-art\s*\{[\s\S]*height:\s*108px/)
        expect(css).toMatch(/\.reader-actions\s*\{[\s\S]*justify-content:\s*flex-end/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-bookmark\s*\{[\s\S]*display:\s*none/)
        expect(css).toMatch(/\.reader-bookmark-role\s*\{[\s\S]*display:\s*none/)
        expect(css).toMatch(/\.reader-meta\s*\{[\s\S]*min-height:\s*40px/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-name\s*\{[\s\S]*font-size:\s*15px/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-header\s*\{[\s\S]*margin-top:\s*-/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-header\s*\{[\s\S]*background:\s*transparent/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-body\s*\{[\s\S]*padding-top:\s*1\.06rem/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-body\s*\{[\s\S]*padding-bottom:\s*1\.22rem/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-meta\s*\{[\s\S]*border-bottom:\s*none/)
        expect(css).toMatch(/@media \(max-width: 640px\)[\s\S]*\.reader-actions\s*\{[\s\S]*justify-content:\s*center/)
    })
})
